[FEAT] 이전 도메인으로 요청이 들어왔을 때 리다이렉트 처리
JNU-econovation/EEOS-BE pull request #174
Opened 2024-11-01 01:15 UTC by kssumin

## 📌 관련 이슈
closed #173 

## ✒️ 작업 내용

### 스크린샷 🏞️ (선택)

## 💬 REVIEWER에게 요구사항 💬

2024-11-01 11:29 UTC, rlajm1203 commented
도메인이 eeos.econo.store 말고 econo.eeos.store 입니다!

새로 만든 도메인은 econo.co.kr 이에요!

2024-11-01 11:31 UTC, rlajm1203 requested changes

2024-11-01 11:31 UTC, rlajm1203 commented on eeos/proxy/nginx.conf
> +        server_name eeos.econo.co.kr;
eeos.econo.co.kr -> eeos.co.kr 로 변경 부탁드려도 될까요?!

2024-11-01 13:39 UTC, kssumin commented on eeos/proxy/nginx.conf
> +        server_name eeos.econo.co.kr;
생각해보니깐...

## 기존 도메인
* 프론트 : econo.eeos.store
* 백엔드 : eeos.store

였더라구요!!

그래서 아래와 같이 변경했습니다!! 확인해주세요!

## 새로운 도메인
* 프론트 : econo.eeos.co.kr
* 백엔드 : eeos.co.kr

2024-11-01 13:50 UTC, kssumin commented on eeos/proxy/nginx.conf
> +        server_name eeos.econo.co.kr;
처음에는 이전 도메인(econo.eeos.store)에서 새 도메인(econo.eeos.co.kr)으로의 리다이렉트를 백엔드에서 구현했었는데요, 이를 다시 검토해보니:

### 도메인 리다이렉트는 본질적으로 프론트엔드 영역의 책임이 더 적절합니다
* Vercel의 설정(vercel.json)으로 처리하는 것이 올바른 방향

### 그렇다면 백엔드가 리다이렉트를 구현한 이유는?
* 프론트엔드에서 URI 변경 작업이 완료되기 전까지 서비스의 안정성 보장이 목적
* 즉, 이전 도메인으로 요청이 들어와도 서버가 정상적으로 동작할 수 있도록 하는 안전장치
* 사용자 경험 저하를 방지하기 위한 과도기적 조치

### 앞으로의 방향
* 프론트엔드의 URI 변경이 완전히 완료될 때까지는 현재 구현을 유지
* 백엔드는 점진적으로 이 리다이렉트 로직을 제거할 예정

2024-11-04 05:27 UTC, rlajm1203 commented on eeos/proxy/nginx.conf
> +        server_name eeos.econo.co.kr;
@kssumin 엇 새로운 프론트 도메인은 www.eeos.co.kr 인 것 같아요!

2024-11-04 05:29 UTC, kssumin commented on eeos/proxy/nginx.conf
> +        server_name eeos.econo.co.kr;
네네 근데 저희 입장에서 지금 프론트 도메인 리다이렉트를 고려할 게 아니고

CORS만 신경쓰면 되지 않나요..?(env파일)

2024-11-04 05:29 UTC, kssumin commented on eeos/proxy/nginx.conf
> +        server_name eeos.econo.co.kr;
아아 위에 제가 쓴 새로운 도메인의 프론트 부분때문이시군요!

넵넵 반영해두겠습니다

다만 코드상의 변경은 없는 게 맞을 것 같습니다

2024-11-04 05:30 UTC, rlajm1203 commented on eeos/proxy/nginx.conf
> +        server_name eeos.econo.co.kr;
BE가 리다이렉트를 구현한 이유는,

BE 서버도 도메인이 변경 되었기 때문에, 만약에라도 이전 도메인으로 API 요청이 들어올 경우에 새로운 도메인으로 요청을 바꿔주도록 하기 위함이군요~

만약 FE는 새로운 도메인을 적용했는데, BE는 이전 도메인을 사용한다면 아마 CORS가 발생하지 않을까 생각이 드네요 그래서 여러 도메인을 허용해줘야 하고요

2024-11-05 13:18 UTC, merged