[REFACTOR] 코멘트 내용 글자수 500자 제한 해제
JNU-econovation/EEOS-BE pull request #185
Opened 2024-11-29 07:30 UTC by rlajm1203

## 📌 관련 이슈
#184 

## ✒️ 작업 내용
코멘트 생성시 validateCreate 로, 글자수 500자 초과인지 검증을 하고 있는데, 이 로직을 수정하여 글자수 500자 제한을 없앴습니다.

이전에 글자수 제한이 500자였다는 것을 기록하기 위해서, 로직 삭제하지 않고 로직을 변경하였습니다.

### 스크린샷 🏞️ (선택)

## 💬 REVIEWER에게 요구사항 💬

2024-11-30 06:39 UTC, Daae-Kim approved these changes
감사합니다! 👍🏻 
ci 통과를 위해 spotless 적용을 해보아요~!

2024-12-13 08:37 UTC, kssumin approved these changes

2024-12-13 08:37 UTC, kssumin commented on eeos/src/test/java/com/blackcompany/eeos/comment/application/model/CommentModelTest.java
> +		String length_501_word =
```suggestion
String length_501_word = new Random().ints(32, 127)
        .limit(501)
        .mapToObj(i -> String.valueOf((char) i))
        .collect(Collectors.joining());
}
```

이런식으로 랜덤 문자열을 생성해보는 건 어떨까요? 나중에 규칙이 변하더라도 쉽게 변경가능할 것 같아요~!

2024-12-13 08:39 UTC, kssumin requested changes

2024-12-13 08:39 UTC, kssumin commented on eeos/src/main/resources/application-local-mysql.yml
> +    password: gksktodaud1!
해당 설정들 변경 이유를 알 수 있을까요?
만약 이 부분이 변경되면 docker-compose 파일도 변경이 되어야 할 것 같습니다.

2024-12-13 08:39 UTC, kssumin commented on eeos/src/main/resources/application-local-redis.yml
> +    port : 6379
위와 동일합니다.

2024-12-13 08:40 UTC, rlajm1203 commented on eeos/src/main/resources/application-local-redis.yml
> +    port : 6379
엇 그 파일 로컬에서 테스트 하기 위해서 변경했는데 같이 커밋이 되었나보네요 ㅠ 얼른 수정하겠습니다~

2025-02-02 09:42 UTC, kssumin approved these changes

2025-02-02 09:44 UTC, merged